Repository bellshade/OpenSeriesWeb, pull requests merged in 2024-02, with the labels that each got.

#8 docs: Menambahkan beberapa penjelasan
  app/docs/fisika/masa-jenis/page.mdx
Labels: ready-to-merge

#9 docs: Menambahkan beberapa dokumentasi
  app/docs/fisika/energi-potensial/page.mdx
Labels: ready-to-merge

#11 fix: background navbar links in dark mode
  components/Navbar.tsx
Labels: ready-to-merge

#13 Docs: diameter,keliling,luas lingkaran
  app/docs/matematika/diameter-lingkaran/page.mdx
  app/docs/matematika/keliling-lingkaran/page.mdx
  app/docs/matematika/luas-lingkaran/page.mdx
Labels: ready-to-merge

#21 docs: Mengubah beberapa Dokumentasi Matematika
  app/docs/matematika/diameter-lingkaran/page.mdx
  app/docs/matematika/faktorial/page.mdx
  app/docs/matematika/keliling-lingkaran/page.mdx
  app/docs/matematika/luas-lingkaran/page.mdx
  app/docs/matematika/persamaan-kuadrat/page.mdx
  app/docs/matematika/radian-ke-derajat/page.mdx
  constants/documentations.ts
Labels: ready-to-merge

#25 chore: create pr build workflow
  .github/workflows/pr-build.yaml
Labels: ready-to-merge

#40 docs: menambahkan dokumentasi matematika
  app/docs/matematika/fpb/page.mdx
  app/docs/matematika/sigmoid/page.mdx
  constants/documentations.ts
Labels: ready-to-merge

#58 docs: add more about OpenSeries & change banner url
  app/docs/page.mdx
  public/assets/img/banner.png
Labels: ready-to-merge, documentation mdx

#59 feat: change navbar design to stacked on mobile screen & add breadcrumbs
  components/Breadcrumbs.tsx
  components/Navbar.tsx
  components/Sidebar.tsx
  hooks/useSidebarStore.ts
Labels: OpenSeries typescript

#60 chore: add codeowners
  .github/CODEOWNERS
Labels: ready-to-merge

#61 feat: add navbar sidebar overlay & remove unnecessary nav links
  components/Navbar.tsx
  components/Sidebar.tsx
  constants/featuredLinks.ts
  constants/navLinks.ts
Labels: ready-to-merge, OpenSeries typescript

#62 chore: change naming convention
  app/(landing)/layout.tsx
  app/(landing)/page.tsx
  app/docs/bilangan/bilangan-armstrong/page.mdx
  app/docs/bilangan/bilangan-automorphic/page.mdx
  app/docs/bilangan/bilangan-pronic/page.mdx
  app/docs/bilangan/bilangan-segitiga/page.mdx
  app/docs/fisika/efek-doppler/page.mdx
  app/docs/fisika/energi-kinetik/page.mdx
  app/docs/fisika/energi-potensial/page.mdx
  app/docs/fisika/gaya-sentripetal/page.mdx
  app/docs/fisika/hukum-ohm/page.mdx
  app/docs/fisika/kecepatan/page.mdx
  app/docs/fisika/masa-jenis/page.mdx
  app/docs/fisika/massa-jenis/page.mdx
  app/docs/fisika/percepatan/page.mdx
  app/docs/fisika/tekanan-barometrik/page.mdx
  app/docs/get-started/tentang/page.mdx
  app/docs/komunitas/page.mdx
  app/docs/kontribusi/page.mdx
  app/docs/layout.tsx
  app/docs/matematika/diameter-lingkaran/page.mdx
  app/docs/matematika/distribusi-binomial/page.mdx
  app/docs/matematika/faktor-prima/page.mdx
  app/docs/matematika/faktorial/page.mdx
  app/docs/matematika/fpb/page.mdx
  app/docs/matematika/integral/page.mdx
  app/docs/matematika/keliling-lingkaran/page.mdx
  app/docs/matematika/luas-lingkaran/page.mdx
  app/docs/matematika/peluang-kejadian/page.mdx
  app/docs/matematika/persamaan-kuadrat/page.mdx
  app/docs/matematika/radian-ke-derajat/page.mdx
  app/docs/matematika/sigmoid/page.mdx
  app/docs/matematika/turunan/page.mdx
  app/docs/page.ts
  app/docs/statistika/entropy/page.mdx
  app/docs/statistika/standar-deviasi/page.mdx
  app/layout.tsx
  components/codeblock/index.tsx
  components/community/index.tsx
  components/contribute/index.tsx
  components/contributors/contributor.tsx
  components/contributors/index.tsx
  components/landing-svg/index.tsx
  components/navbar/breadcrumbs.tsx
  components/navbar/index.tsx
  components/sidebar/index.tsx
  components/theme-provider/index.tsx
  components/theme-switcher/index.tsx
  constants/core-team.ts
  constants/documentations.ts
  constants/featured-links.ts
  constants/nav-links.ts
  constants/project-by-links.ts
  constants/social-links.ts
  stores/use-nav-style-store.ts
  stores/use-sidebar-store.ts
Labels: ready-to-merge, OpenSeries typescript, documentation mdx

#63 chore: add sort import prettier
  .pre-commit-config.yaml
  .prettierrc
  app/(landing)/layout.tsx
  app/(landing)/page.tsx
  app/docs/layout.tsx
  app/layout.tsx
  bun.lockb
  components/codeblock/index.tsx
  components/contribute/index.tsx
  components/contributors/index.tsx
  components/navbar/index.tsx
  components/sidebar/index.tsx
  components/theme-provider/index.tsx
  next.config.mjs
  package.json
  tailwind.config.ts
Labels: ready-to-merge, OpenSeries typescript

#64 chore: update eslint config
  .eslintrc.json
  app/docs/layout.tsx
  app/layout.tsx
  bun.lockb
  components/community/index.tsx
  components/contribute/index.tsx
  components/contributors/index.tsx
  components/landing-svg/index.tsx
  components/navbar/breadcrumbs.tsx
  components/navbar/index.tsx
  components/sidebar/index.tsx
  components/theme-provider/index.tsx
  constants/documentations.ts
  package.json
  stores/use-sidebar-store.ts
Labels: ready-to-merge, OpenSeries typescript

#65 feat: automate sidebar links
  .prettierrc
  app/docs/layout.tsx
  bun.lockb
  components/docs-wrapper/index.tsx
  components/sidebar/index.tsx
  constants/documentations.ts
  constants/sidebar-links.ts
  package.json
  utils/get-docs.ts
Labels: ready-to-merge, OpenSeries typescript

#66 fix: komunitas not found
  constants/nav-links.ts
Labels: ready-to-merge

#68 fix: svg animation too heavy
  app/globals.css
  components/landing-svg/index.tsx
Labels: ready-to-merge, OpenSeries typescript

#69 add: meta keywords, applicationName, creator, openGraph image
  app/layout.tsx
Labels: ready-to-merge, OpenSeries typescript

#71 fix: metadataBase url
  app/layout.tsx
Labels: ready-to-merge, OpenSeries typescript

#70 docs: improvisasi kata dan layout untuk README.md dan CONTRIBUTING.md
  .github/banner.png
  CONTRIBUTING.md
  LICENSE
  README.md
Labels: ready-to-merge

#72 fix: refactor css (pengtailwind-an masal cuy)
  app/(landing)/page.tsx
  app/globals.css
  bun.lockb
  components/landing-svg/index.tsx
  package.json
  postcss.config.js
Labels: ready-to-merge, OpenSeries typescript

#73 chore: add postbuild for sitemap
  .gitignore
  bun.lockb
  next-sitemap.config.js
  package.json
Labels: ready-to-merge

#74 chore: add markdownlint
  .markdownlint.jsonc
  .pre-commit-config.yaml
  .prettierignore
  CONTRIBUTING.md
  README.md
  bun.lockb
  package.json
Labels: ready-to-merge

#76 chore: update pr-build.yaml
  .github/workflows/build-openseries-web.yaml
  .github/workflows/pr-build.yaml
Labels: ready-to-merge, ready to review

#81 chore: create issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/contribute-request.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: ready-to-merge, ready to review

#84 fix: svg animation on system theme
  components/landing-svg/index.tsx
  postcss.config.mjs
  prettier.config.js
Labels: ready-to-merge, OpenSeries typescript, ready to review

#85 fix: responsive code block
  components/codeblock/index.tsx
Labels: ready-to-merge, OpenSeries typescript, ready to review

#87 fix: performance & accessibility
  app/(landing)/page.tsx
  app/layout.tsx
  bun.lockb
  components/landing-svg/index.tsx
  components/navbar/breadcrumbs.tsx
  components/navbar/navbar-content.tsx
  components/sidebar/index.tsx
  components/theme-switcher/index.tsx
  mdx-components.tsx
  package.json
Labels: ready-to-merge, OpenSeries typescript, ready to review
